name: WkKit
main: cn.wekyjay.www.wkkit.WkKit
version: '${project.version}'
api-version: 1.13
author: WekyJay
description: A minecraft plugin by WekyJay.
website: https://forum.wekyjay.cn/
folia-supported: true
softdepend: 
   - PlaceholderAPI
   - Vault
   - MythicMobs
   - ItemsAdder
commands:
  wkkit:
    description: Get plugin helper.
    permission: wkkit.help
    permission-message: You do not have permission!
    usage: /<command> help
    aliases: 
       - wk
permissions:
  wkkit.*:
    description: Wildcard permission
    default: op
    children:
      wkkit.help: true
      wkkit.open: true
      wkkit.mail: true
      wkkit.get: true
      wkkit.cdk.*: true
  wkkit.help:
    default: true
  wkkit.open:
    default: true
  wkkit.mail:
    default: true
  wkkit.get:
    default: true
  wkkit.cdk.*:
    default: true
    children:
      wkkit.cdk.verify: true
      wkkit.cdk.exchange: true